name: Compile Action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run latexmk
        run: "latexmk main.tex"
      - name: add permissions
        run: "git config --global --add safe.directory /__w/10PointProgram/10PointProgram"
      - name: Store build timestamp
        run: echo "BUILD_TIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
      - name: change file name
        run: "mv main.pdf main$BUILD_TIME.pdf"
      - name: add and commit
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.pdf'
     # - name: Archive document
     #   uses: actions/upload-artifact@v4
     #   with:
     #     name: document
     #     path: "./*.pdf"
